### ISSUE TITLE
song or notification not appearing while not in a gui

### ISSUE THREAD

**Issue by z4xi** [ThatGravyBoat/Craftify#10]
it just doesn't appear 🤷 

## screenshots:

in gui
![image](https://user-images.githubusercontent.com/36055611/174688360-8a277a23-1e68-4dc8-9ad6-a4a490d95269.png)

out of gui
![image](https://user-images.githubusercontent.com/36055611/174688381-a5380a1f-e304-41a7-b827-2138e59c9ef3.png)

don't know if this is a bug or me just being dumb, but I set the render type to always so idk 🤷

**Comment by ThatGravyBoat** [comment]
check your render mode setting in `/craftify` to see if you have it on `Escape Menu Only`
