### ISSUE TITLE
Control Buttons show up as error icon but still function

### ISSUE THREAD

**Issue by Bwopp** [ThatGravyBoat/Craftify#103]
https://media.essential.gg/c6dd3cde-c652-4815-c1e9-20c9931bb000

I have tried resetting the theme config and removing the config files. All the buttons still work, but I can't tell what they are.

**Comment by Bwopp** [comment]
Fixed since

**Comment by SayoKurokawa** [comment]
I have the same issue tho

**Comment by ThatGravyBoat** [comment]
do /craftify library and click install on the theme again to resolve the issue
