### ISSUE TITLE
Controls barely work / delayed action (Spotify)

### ISSUE THREAD

**Issue by SayoKurokawa** [ThatGravyBoat/Craftify#104]
I had the mod for a while now but never used it. I just downloaded the newest version for fabric 1.20.1. 
The controls don't work most of the time. If they work they are often delayed. The Display is also delayed a lot.
I tried restarting the game but that didnt help. I do have Spotify Premium.

**Comment by ThatGravyBoat** [comment]
Spotify does not have a websocket api so to get information from your app Craftify has to poll the app as recommended by Spotify themseleves so the display only updates every 2 seconds, if it is delayed then this is due to your internet connection

**Comment by SayoKurokawa** [comment]
My internet connection is fine tho and the controls still don't work most of the time.
