### ISSUE TITLE
[`1.20.1] Craftify crashing Sinytra Connector 

### ISSUE THREAD

**Issue by Starexify** [ThatGravyBoat/Craftify#106]
I encountered this crash when trying to load Craftify in Forge using Sinytra Connector:

https://gist.github.com/Starexify/e726a19a1cdd4197b76c9dc14cb2f202

I reported to the Connector and the developer said this is a problem with the mod, it includes classes in a package that begins with `java.`, which is prohibited by the JVM. 

More here: https://github.com/Sinytra/Connector/issues/959#issuecomment-2040664301

I just wanted to report this since more compatibility between mods is better.

**Comment by ThatGravyBoat** [comment]
Will be fixed when this gets merged https://github.com/EssentialGG/UniversalCraft/pull/73

**Comment by ThatGravyBoat** [comment]
This has been fixed
