### ISSUE TITLE
Doesn't work with Essential

### ISSUE THREAD

**Issue by nmsltr** [ThatGravyBoat/Craftify#108]
I downloaded Craftify into my build where Essential was already installed and it gave me this error.

![image](https://github.com/ThatGravyBoat/Craftify/assets/165626136/f0fcb9e8-5d30-4e2c-8eff-003f09e130d5)

I tried removing Essential and Dependencies configs and everything works fine. I want to use these two mods but I don’t know how to fix this error.

**Comment by ThatGravyBoat** [comment]
This is an issue where essential tries to inject into how mods are loaded and does not respect a system in fabric called JiJ
