### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Cyhopsycho** [ThatGravyBoat/Craftify#110]
![image](https://github.com/ThatGravyBoat/Craftify/assets/101393100/6ddddf7f-a7cb-4730-99ae-c42eadf60790)
can't access craftify

**Comment by Cyhopsycho** [comment]
also /craftify crashes the game

**Comment by ThatGravyBoat** [comment]
what mc version are you on?

**Comment by Cyhopsycho** [comment]
1.20.6 fabric

**Comment by ThatGravyBoat** [comment]
Fabric 1.20.6 is not supported yet.

**Comment by Cyhopsycho** [comment]
sweet.
