### ISSUE TITLE
Icons not being fetched from Imgur and displaying backup "⚠️" icon in black in their place

### ISSUE THREAD

**Issue by SamHammie** [ThatGravyBoat/Craftify#114]
![image](https://github.com/ThatGravyBoat/Craftify/assets/28793227/9bd74902-40e2-4070-9423-8d65789d0fe0)

Fabric 0.15.11 on Minecraft 1.20.1 with Craftify version 0.14.0 and Essential version 1.3.2.4

**Comment by ThatGravyBoat** [comment]
do /craftify library and click install on the default theme until I can release an update fixing it
