### ISSUE TITLE
[SUGGESTION] Release the mod files on GitHub

### ISSUE THREAD

**Issue by j10a1n15** [ThatGravyBoat/Craftify#115]
I heard that there is an Update, but like where do I find the updated files? There isnt even a potential discord server linked, where the new version could be.
Please publish releases on GitHub :pray:

**Comment by ThatGravyBoat** [comment]
I wont be releasing updates on GitHub as GitHubs moderation is lack luster so I do not want people to expect to find it on github to only end up on the wrong page and then get their privacy or computer compromised by a malicious actor injecting code into a release and creating a fake page.

All releases and released on Modrinth and CurseForge

Heres a link using my Modrinth linking service: https://mods.gay/craftify

**Comment by ThatGravyBoat** [comment]
I will update the description to show where to find it though

**Comment by j10a1n15** [comment]
> I will update the description to show where to find it though

Sick, thank you :pray:

**Comment by RayDeeUx** [comment]
@ThatGravyBoat late response but could the readme also include tidal-hifi installation instructions in light of today's update?
