### ISSUE TITLE
Suport for last FM

### ISSUE THREAD

**Issue by lukee12zakk** [ThatGravyBoat/Craftify#118]
Would It be posible to add suport for Lastfm?

**Comment by ThatGravyBoat** [comment]
What exactly would be adding support for lastfm do? isnt lastfm just a service to show like trending songs and have a catalog of your music, and not a streaming service?

**Comment by lukee12zakk** [comment]
Basically, it is like the spotify plugin to show what is playing. So if I use SpotTube, an app that has last fm integration( basically  it tells lastfm what you are listening to) to display the song playing in game.

**Comment by ThatGravyBoat** [comment]
I looked into this more, sadly this is not possible due to the limitations of lastfm they do not support all the things required for it to work with Craftify.
