### ISSUE TITLE
Controls hardly work and songs take a long time to be found

### ISSUE THREAD

**Issue by Axerium** [ThatGravyBoat/Craftify#120]
They only work sometimes, if at all. When they do they are a bit laggy, and the songs take around 30 seconds to be found and put on the screen. Sometimes the GUI will just disappear altogether.
I have Premium, I have restarted multiple times. deleted mods and resource packs to see if it's lag in Minecraft that's causing it, my internet connection is pretty much perfect in all other contexts so I don't believe it's that.

**Comment by Axerium** [comment]
I'm on Fabric 1.20.6.

**Comment by DanDragonWolf** [comment]
> I'm on Fabric 1.20.6.

There's a setting for Spotify in the rendering section for being able to control Spotify, turn that on

**Comment by DanDragonWolf** [comment]
> If your internet is fine then the only other thing is Spotify actually takes that long to process the data. Make sure you're using an up to date Spotify app.

Apparently a few commands will go through even if controls is turned off, they just need to turn it on

**Comment by Axerium** [comment]
> > I'm on Fabric 1.20.6.
> 
> There's a setting for Spotify in the rendering section for being able to control Spotify, turn that on

The controls setting has been on this entire time.

**Comment by DanDragonWolf** [comment]
> > > I'm on Fabric 1.20.6.
> > 
> > 
> > There's a setting for Spotify in the rendering section for being able to control Spotify, turn that on
> 
> The controls setting has been on this entire time.

You sure? Make sure the slider is blue and not gray, I made that mistake. Also, Spotify integration is a bit buggy anyways for some reason, I don't think Spotify likes being controlled by other applications

**Comment by Axerium** [comment]
> > > > I'm on Fabric 1.20.6.
> > > 
> > > 
> > > There's a setting for Spotify in the rendering section for being able to control Spotify, turn that on
> > 
> > 
> > The controls setting has been on this entire time.
> 
> You sure? Make sure the slider is blue and not gray, I made that mistake. Also, Spotify integration is a bit buggy anyways for some reason, I don't think Spotify likes being controlled by other applications

I am sure, and I checked after you sent your last reply. I'm aware that it can be a little buggy, I guess I'm now just confused because I use Spotify controls with Vencord and that works much better in regards to lagginess and stuff like that.
