### ISSUE TITLE
Play, pause and skip buttons don't work

### ISSUE THREAD

**Issue by Liam040** [ThatGravyBoat/Craftify#124]
So basically, all the buttons in the quick menu dont work, except the volume. It does say which song is playing and the time, but i can't change anything about the song. Im on 1.20.6 and i am currently using Craftify-1.20.6.-1.16.0-fabric.

**Comment by ThatGravyBoat** [comment]
if you are using spotify make sure you have Spotify premium, if you are using YTMD make sure you have playback controls on

**Comment by Liam040** [comment]
Update: I moved the little box and now it works, but very inconsistent.  Sometimes it works 5 times in a row and sometimes I press it 10 times and it doesnt work. I do have spotify premium.
