### ISSUE TITLE
Spotify Login

### ISSUE THREAD

**Issue by LynxarA-Coding** [ThatGravyBoat/Craftify#125]
When I login to Spotify, it redirects to non-existing localhost page
![image](https://github.com/user-attachments/assets/01a31455-1b13-4fc2-b5ae-c24aeac2808d)
![image](https://github.com/user-attachments/assets/b7357737-4e57-4047-9987-b49e76c4dd92)

**Comment by ThatGravyBoat** [comment]
You need to start the login process via in-game it will start the local login server and that is where it should redirect you to

**Comment by LynxarA-Coding** [comment]
Thats what I've done, but the redirect from the game opens the "Can't reach" website

**Comment by ThatGravyBoat** [comment]
Im gonna close this since its been months, I think this issue was due to some connection issue with your browser, if it still continues please open a new report
