### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by EvilTai** [ThatGravyBoat/Craftify#128]
how do i get the mod to connect to my spotify?

**Comment by DoggoNako** [comment]
In the chat, type: ` /craftify `.
A screen that looks like Essential's menu will open.
In "Music Service", click to open the list, then select Spotify and click on the cogwheel icon.
A pop up will appear, in "Login" click on the "Activate" button (This will make your default browser appear on the [Craftify Login Screen](https://craftify.thatgravyboat.tech/login)) 
Now click "Login", you'll need to connect to your Spotify account and accept what craftify needs to show you the image and title of the song you're listening to.

You should now be connected (sometimes it takes a second or two). If not, you may have waited too long to sign in to your account.

I've made a GIF to show how it should be done (at least how I made it work).
![Animation](https://github.com/user-attachments/assets/d1fe948b-1b05-4137-a8f6-be422dea2f00)

**Comment by ThatGravyBoat** [comment]
thanks @DoggoNako

**Comment by EvilTai** [comment]
you're the best
