### ISSUE TITLE
Tidal service isn't working

### ISSUE THREAD

**Issue by DoggoNako** [ThatGravyBoat/Craftify#129]
I've been trying to get the Tidal service to work, but (at least in France) I don't have the "Web API" and "Playback Control" options.

It could be because Tidal is changing their application and their API.

Here is the documentation for both, their API and their SDK
https://developer.tidal.com/documentation

If needed, I'm can be here to test

**Comment by Nagisa723** [comment]
For me in Switzerland those options don't exist either. Also when searching for those options via Internet, you find nothing about it.

**Comment by Nagisa723** [comment]
Thanks for your answer :D

**Comment by ThatGravyBoat** [comment]
Tidal in Craftify uses this service due to Tidal not responding to my developer support tickets and such https://github.com/Mastermindzh/tidal-hifi
