### ISSUE TITLE
Skip not working

### ISSUE THREAD

**Issue by cumpowder123** [ThatGravyBoat/Craftify#14]
I have craftify installed along with essential and some other mods the skip isnt working i have spotify premium ive changed the controls it still doesnt work not sure what to do

**Comment by ThatGravyBoat** [comment]
provide lastest.log

**Comment by cumpowder123** [comment]
[latest.log](https://github.com/ThatGravyBoat/Craftify/files/9420089/latest.log)

**Comment by ThatGravyBoat** [comment]
I'm gonna close for now if the problem persists open another issue but as of right now in newer versions the system that runs this has changed so I cant even find the issue.
