### ISSUE TITLE
cant link spotify

### ISSUE THREAD

**Issue by TheCorruptCat** [ThatGravyBoat/Craftify#21]
when i try to link it it takes me to
localhost:21851/login
but its blank

**Comment by ThatGravyBoat** [comment]
Cna you send a screenshot

**Comment by idkh3lpme** [comment]
happening to me too
![image](https://user-images.githubusercontent.com/118058718/209013226-d4a7e2ae-cc21-4add-9aea-a56fb5b8c7bf.png)

**Comment by idkh3lpme** [comment]
> Cna you send a screenshot

Ik im not the one who opened the issue but its happening to me too on firefox
![image](https://user-images.githubusercontent.com/118058718/209013314-8bc9ff04-50fa-42d2-8034-23077e2597df.png)

**Comment by TheCorruptCat** [comment]
that is it

**Comment by TheCorruptCat** [comment]
that is the problem

**Comment by ToxicXremade** [comment]
> that is the problem

what?

**Comment by ToxicXremade** [comment]
> > that is the problem
> 
> what?

because I tried this in microsoft edge and it didn't work either
imma download chrome and try it there too

**Comment by TheCorruptCat** [comment]
chrome does not work too

**Comment by ToxicXremade** [comment]
> chrome does not work too

so then what does

**Comment by ToxicXremade** [comment]
> > chrome does not work too
> 
> so then what does

or is this an issue thats actually the mod's fault

**Comment by TheCorruptCat** [comment]
> > chrome does not work too
> 
> so then what does

nothing

**Comment by TheCorruptCat** [comment]
maybe downgrading the mod would work

**Comment by TheCorruptCat** [comment]
1.4.1 works

**Comment by ThatGravyBoat** [comment]
send your minecraft logs when you try to open the link

**Comment by TheCorruptCat** [comment]
![problem 2](https://user-images.githubusercontent.com/121116702/209163900-6da99db8-34bb-40f1-a2fc-abdc7ad3e2ea.png)

**Comment by TheCorruptCat** [comment]
this also happends

**Comment by TheCorruptCat** [comment]
on 1.4.1 and 1.4.0

**Comment by ThatGravyBoat** [comment]
> 

The the reason that happens on 1.4.1 is because it had a bug which was fixed in 1.5.0

**Comment by TheCorruptCat** [comment]
[latest.log](https://github.com/ThatGravyBoat/Craftify/files/10287933/latest.log)

**Comment by TheCorruptCat** [comment]
but 1.5.0 wont let me link spotify

**Comment by ThatGravyBoat** [comment]
I need a log from 1.5.0 not 1.4.0
I can load and use 1.5.0 fine so I need someone that is experiencing the bug to send me a log

**Comment by TheCorruptCat** [comment]
[latest.log](https://github.com/ThatGravyBoat/Craftify/files/10287950/latest.log)

**Comment by TheCorruptCat** [comment]
got it

**Comment by TheCorruptCat** [comment]
and

**Comment by TheCorruptCat** [comment]
![prtdfthyfc](https://user-images.githubusercontent.com/121116702/209164959-fbfe8848-3abe-4257-b278-d55aed3db689.png)

**Comment by ThatGravyBoat** [comment]
can you try on fabric not quilt

**Comment by TheCorruptCat** [comment]
I got a screenshot

**Comment by TheCorruptCat** [comment]
also i have linux

**Comment by ThatGravyBoat** [comment]
yeah so it sounds like quilt broke something idk how because all I do it create a normal website but quilt somehow broke it.

So just want to confirm switching from quilt to fabric fixed it?

**Comment by ToxicXremade** [comment]
> yeah so it sounds like quilt broke something idk how because all I do it create a normal website but quilt somehow broke it.
> 
> So just want to confirm switching from quilt to fabric fixed it?

Aight I will try fabric and confirm
too bad essential doesn't support quilt so then craftify could support it

**Comment by ThatGravyBoat** [comment]
/remind me about this in 4 hours to see if a response has been posted if not close

**Comment by TheCorruptCat** [comment]
it did

**Comment by TheCorruptCat** [comment]
> yeah so it sounds like quilt broke something idk how because all I do it create a normal website but quilt somehow broke it.
> 
> So just want to confirm switching from quilt to fabric fixed it?

it did

**Comment by TheCorruptCat** [comment]
yea it fixed it
