### ISSUE TITLE
Incompatable with Optifabric

### ISSUE THREAD

**Issue by 4NG3L-D4RKS1DE** [ThatGravyBoat/Craftify#23]
You might know this, but it'd be nice to put it somewhere on the mod site.
My progress bar is yellow, and turning on "background color" at all turns the rest yellow. I canceled out shaders and resource packs, and managed to find it was indeed optifabric. I hope theres a fix, if not then there isn't.

If you need screenshots of the issue just let me know!

**Comment by ThatGravyBoat** [comment]
yeah I would like screenshots

**Comment by ThatGravyBoat** [comment]
I would also like to mention that optifine and optifabric by extension is not supported by a lot of mod developers optifine is very poor developed and does not really consider compatibility with anything so it breaks with a lot of mods. I would suggest using something like iris, sodium, and continuity as they are far better at compatibility.

**Comment by 4NG3L-D4RKS1DE** [comment]
I know I should use those, it has caused problems but I have more things that need it so I kinda just deal with it. I just wonder if bugs can be fixed, you know.
The explanations were up there, but Background Color makes all of it yellow, just like the progress bar is stuck as. And then the obvious progress bar being that color.
![Screenshot (4032)](https://user-images.githubusercontent.com/67876166/210282538-99d53583-8fa6-481b-b5cb-ff0e31c65842.png)
![Screenshot (4030)](https://user-images.githubusercontent.com/67876166/210282542-a96cbd35-2a1d-428a-91f0-cd729254b7bb.png)

**Comment by ThatGravyBoat** [comment]
it cant be fixed on my end I use Elementa for that so it would have to be fixed in that but it sounds like optifabric does some really funky stuff for color to just not work correctly

**Comment by 4NG3L-D4RKS1DE** [comment]
Alright, thank you for at least looking at it! Have a good day :)
