### ISSUE TITLE
logo update

### ISSUE THREAD

**Issue by vindocel** [ThatGravyBoat/Craftify#24]
looking at the name of the project and seeing the current logo, I felt free to create the project's logo in pixelated style to better match the minecraft theme, I hope you like it.
![Craftify-HEADER](https://user-images.githubusercontent.com/18473368/210639229-965b7fb9-129b-4417-b1c9-5bd358e02f93.png)
![Craftify-LOGO-WITH BACKGROUND](https://user-images.githubusercontent.com/18473368/210639233-39de606d-0b43-4eb0-9951-44ef29cc7d78.png)

[Craftify.zip](https://github.com/ThatGravyBoat/Craftify/files/10347078/Craftify.zip)

**Comment by Hir0shiyt** [comment]
I'd upvote this, cuz the theme of the mod is to mix spotify ehich has a rounded logo and minecraft which is made out of blocks/squares and these ar esome beatiful pieces of pixel art being thrown to the trash if not used

**Comment by ThatGravyBoat** [comment]
I appreciate the assets if you could do so and PR them to https://github.com/Craftify-Mod/Assets so that it is done in an official manner and that a contributor license agreement can be signed so that I can be sure I can use it without legal troubles in the future.
