### ISSUE TITLE
Youtube music Desktop app

### ISSUE THREAD

**Issue by BongwaterBilly420** [ThatGravyBoat/Craftify#26]
How do you go about setting up ytmd as i followed this: https://imgur.com/a/SUd1Rf8 but i cant find the integrations area. is it this link im meant to use?: https://music.youtube.com/ or do u download it somewhere?

**Comment by ThatGravyBoat** [comment]
It's a community-made app for YouTube Music so you don't need a browser, this is what has the integration as YouTube themselves don't provide an API for developers like me to use for integration like this. 

https://ytmdesktop.app/
