### ISSUE TITLE
[Suggestion] Open source

### ISSUE THREAD

**Issue by RaptaG** [ThatGravyBoat/Craftify#28]
Since the code is available to the public, why not make the mod open source with a license that protects the author and their code, such as [GPL-3.0](https://www.gnu.org/licenses/gpl-3.0.en.html)?

**Comment by ThatGravyBoat** [comment]
The reason it does not have an open source license is that this repo is only for the UI and some other small things, the actual library that controls the services is here and open source: https://github.com/ThatGravyBoat/JukeBox

**Comment by RaptaG** [comment]
So can it be considered open source?

**Comment by ThatGravyBoat** [comment]
It is viewable source, I don't really see a reason to make it fully open source with almost all code in the mod dealing with the UI so to copy the code it will likely be used to fully copy the whole mod which someone has tried, so it will stay as viewable source but if there is certain specific code that you would like to use just ask and ill likely allow you to use it.
