### ISSUE TITLE
mod not finding music on spotify

### ISSUE THREAD

**Issue by Krystian43** [ThatGravyBoat/Craftify#31]
when i connected mod with spotify this mod does not show anything
when i type /craftify refresh, still nothing.

**Comment by ThatGravyBoat** [comment]
have you tried restarting the game?

**Comment by Krystian43** [comment]
yes i restart the game and reconnect account still nothing

**Comment by ThatGravyBoat** [comment]
You are likely in a private session I've added a thing to remind people of this in 1.7.0, if the problem persists make a new report with a latest.log file
