### ISSUE TITLE
Can't login, not connecting to localhost

### ISSUE THREAD

**Issue by Icoryx** [ThatGravyBoat/Craftify#32]
When I try to connect the Mod to Spotify it can't open the local site to what I assume give the API key to the mod:

![msedge_ZsWL8LAFMQ](https://user-images.githubusercontent.com/17325607/219511561-034cf082-830d-4691-a2ff-ea19b86868eb.gif)

I'm using Fabric 0.14.14 for 1.19.3 with these Mods:
```diff
+ **_Fabric API 0.74.0_**
# Sodium 0.4.9
# Lithium 0.10.4
# Iris 1.5.2
# LazyDFU 0.1.3
# Starlight 1.1.1
# Entityculling 1.5.2
# Modmenu 5.0.2
# Cloth Config 9.0.94
# Ferrite Core 5.1.0
# Indium 1.0.14
# Reeses Sodium Options 1.4.9
# Sodium Extra 0.4.17
+ **_Fabric Language Kotlin 1.8.10_**
+ **_Craftify 1.6.0_**
# Architectury 7.1.70
# Krypton 0.2.1
# 3D Skin Layers 1.5.2
# Not Chat Reports 2.0.0
# Fabrishot 1.9.1
# Inventory Profiles Next 1.9.2
# REI 10.0.586
```

**Comment by ThatGravyBoat** [comment]
Do you have this issue with the mod by itself?

**Comment by Icoryx** [comment]
With only Fabric API and Kotlin it worked. Should've probably tried that earlier -.-

**Comment by zohfur** [comment]
@Icoryx I'm getting this exact issue with a similar modlist. Did you find out what the cause was?

```
+ **_Fabric API 0.74.0_**
# Sodium 0.4.8
# Lithium 0.10.4
# Iris 1.5.1
# Starlight 1.1.1
# Entityculling 1.6.1
# Modmenu 5.1.0
# Cloth Config 9.0.94
# Ferrite Core 5.1.0
# Indium 1.0.12
# Reeses Sodium Options 1.4.9
# Sodium Extra 0.4.17
+ **_Fabric Language Kotlin 1.9.1_**
+ **_Craftify 1.7.0_**
# Fabrishot 1.9.1
```

**Comment by Icoryx** [comment]
@zohfur hi, unfortunately I didn't find out what mod caused it but after starting craftify with on the dependencies, loggin into spotify and then putting all the mods back in it stayed logged in
