### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by LightningTY** [ThatGravyBoat/Craftify#34]
When I try to login with spotify it just does not work. It doesn't do anything. (spotify is the mod mode)
![image](https://user-images.githubusercontent.com/68978769/223833866-f9582ee8-6ea3-4661-96e8-23ef047143d3.png)

**Comment by ThatGravyBoat** [comment]
What do you exactly mean by "does not work"?

**Comment by LightningTY** [comment]
I press login with spotify and nothing happens. its like the page only refreshes and Im unable to login

**Comment by ThatGravyBoat** [comment]
You are likely using a mod that broke the client side login endpoint.
