### ISSUE TITLE
Control Buttons Not Working

### ISSUE THREAD

**Issue by Razberry314** [ThatGravyBoat/Craftify#35]
I'm using the latest version of craftify on forge 1.8. The buttons aren't showing, and I have to go to the actual spotify app to skip songs.

**Comment by ThatGravyBoat** [comment]
turn the controls on in the craftify settings with /craftify

**Comment by Razberry314** [comment]
Which setting? I don’t see it listed.

**Comment by ThatGravyBoat** [comment]
Rendering > Controls

**Comment by Razberry314** [comment]
I’ll do as soon as I have access to my PC.
