### ISSUE TITLE
Cider 1.6.0 does not work with Craftify on Fabric 1.19.4 (mod version 1.8.0)

### ISSUE THREAD

**Issue by Shodwriter** [ThatGravyBoat/Craftify#36]
Craftify 1.19.4 does not work with Cider 1.6.0. Playing a song using Cider 1.6.0 does not display anything in Minecraft with Craftify 1.8.0. However, using Cider 1.5.9 seems to solve the issue. I'm assuming something's changed with Cider 1.6.0 which is the source of the issue.

**Comment by ThatGravyBoat** [comment]
I've tested this and had it work possibly another issue is at play here.
