### ISSUE TITLE
Doesnt work with Essential on 1.19.4

### ISSUE THREAD

**Issue by ItsAllay** [ThatGravyBoat/Craftify#38]
It says there needs to be a manual restart of UniversalCraft and Elementa, not sure how to do this. Relaunching game doesnt help

**Comment by ThatGravyBoat** [comment]
This seems to be an issue with Essential mod, not me they seem to not care about how the libraries are loaded and assume that Elementa and UniversalCraft are only loaded by them and not other people, you should report this issue to them.

**Comment by SystemlessDev** [comment]
The user in question is using feather client. We restart the game to add a empty mod with Elementa and UC so that we can make use of fabric's dependency resolution system. 
 
The issue is that when we drop the blank mod with our libs, feather overwrites it on next startup.
On game startup, feather will wipe the mods folder and move mods from its own internal folder. 

In other words we can't do much about this.

**Comment by ThatGravyBoat** [comment]
oh, another Feather issue makes sense, I've stopped supporting Feather for other reasons I will let others know if they run into this issue. Is there anything I can do on my end besides having the exact same versions as Essential or is this just completely on Feather?

**Comment by SystemlessDev** [comment]
In theory you can use the same versions as Essential. But honestly I wouldn't really bother. It's just extra maintenance for you. It's completely on feather to get it fixed up (by behaving like any other launcher).

**Comment by ItsAllay** [comment]
Yep, I switched away from feather and it works now. I just use fabric on
multimc now

**Comment by Naile7477** [comment]
I've found a way to work around that problem:
1. get Mod Menu mod
2. Start game (without Essential and Craftify)
3. open with mod menu, the Mods directory
4. let the Mods directory in file explorer open and restart the game
5. start game (this time with Craftify and Essential enabled)
6. copy the mod "Essential Dependencies.temp.jar"
7. paste it on desktop or anywhere else
8. rename the file to "Essential Dependencies.jar"
9. go to feather and click on "add own mod button"
11. paste the "Essential Dependencies.temp.jar" file and enable it
12. Done (Now you can start the game)
