### ISSUE TITLE
Craftify does not support spotify's local files

### ISSUE THREAD

**Issue by hazelnitwit** [ThatGravyBoat/Craftify#39]
When playing a local file in Spotify, it seems that a JSON error occurs which locks up Craftify and results in no song being displayed. Linked below is the client log for my session in 1,19.4 using Quilt Loader 0.18.8 https://mclo.gs/1U3cIjt#L652
This happens both with direct "Local Files" interaction, as well as pseudo-added local files in playlists or liked songs.

If you need any more/specific data, feel free to reply.
Thank you,
Hazel

**Comment by ThatGravyBoat** [comment]
Interesting, ok spotify used to not give me the local files in the API so I never really accounted for it, ill look into it when I can

**Comment by ThatGravyBoat** [comment]
Fixed in 1.9.0
