### ISSUE TITLE
Cider 2.0 Support for Craftify?

### ISSUE THREAD

**Issue by DeadFrostt** [ThatGravyBoat/Craftify#40]
As cider 2 is now nearing its release i would like to ask if you can add cider 2.0 support to craftify. I can provide any help let me know!

**Comment by ThatGravyBoat** [comment]
Yes I would like to support Cider 2.0 I just have to find some time to read how the API has changed

**Comment by ThatGravyBoat** [comment]
I've looked into this and it seems that the WebSocket API was removed from 2.0 which is what I used, I would prefer not to go back in time to the old ages and use HTTP polling, maybe I am missing something but removing the WebSocket doesn't really seem to make much sense.

**Comment by quacksire** [comment]
@ThatGravyBoat, As developer of Cider, specifically our Connect service, we can make it work. We just recently switched to a Firebase and instance based system which could be beneficial in this project. We make the necessary endpoints available to you if you want, just need to make sure it's accessed properly and securely.

Join our [Discord](https://discord.gg/applemusic) and open a ticket where we can discuss further.

**Comment by ThatGravyBoat** [comment]
@quacksire I have joined and made a ticket.

**Comment by Beamy68** [comment]
Any progress on this? It has been months.
