### ISSUE TITLE
Craftify is incompatible with Essential on 1.19.2

### ISSUE THREAD

**Issue by OrigamingWasTaken** [ThatGravyBoat/Craftify#44]
The game will launch, but you will not be able to access certain menus like the Social Menu.

Game version is 1.19.2
Craftify version is 1.9.0
Essential Version is 1.0.0 (apparently? in the logs)

logs: https://mclo.gs/nAHR3xi

**Comment by SystemlessDev** [comment]
Please attempt to recreate this issue without feather. This issue is most likely related to #38.

**Comment by OrigamingWasTaken** [comment]
Issue is still present without feather. The logs are from a friend of mine who had the bug (which I experimented too)

**Comment by Naile7477** [comment]
Posted a workaround:
https://github.com/ThatGravyBoat/Craftify/issues?q=essential+#issuecomment-1848935411
