### ISSUE TITLE
Keybind for Opening Craftify GUI not working

### ISSUE THREAD

**Issue by CH-Tamilzha** [ThatGravyBoat/Craftify#46]
In the **key binds** sections of _Minecraft settings_, there is an option for binding the **GUI of Craftify**. 

However, it doesn't open the Craftify GUI upon pressing. 

Please fix.

**Comment by ThatGravyBoat** [comment]
This is working as intended its just to toggle the current state, it is still dependent on the other render modes and display modes being true.

**Comment by CH-Tamilzha** [comment]
Oh alright...
