### ISSUE TITLE
Craftify is broken by local files again as of 1.10.0

### ISSUE THREAD

**Issue by nitwithazel** [ThatGravyBoat/Craftify#47]
Mod version: 1.10.0
Old issue pre 1.9.0: #39 
A similar JSON error occurs when playing local files alongside mod version 1.10.0
I don't know if it Spotify breaking it or what, but here's the logs.
My logs: https://paste.ee/p/H5yAB
Thank you for your continued development efforts! I find Craftify to be extremely useful and aesthetic

~ hazel

**Comment by Futuremappermydud** [comment]
[latest.log](https://github.com/ThatGravyBoat/Craftify/files/11670952/latest.log)
I am too having this issue

**Comment by ThatGravyBoat** [comment]
Fixed in 1.11.0

**Comment by Futuremappermydud** [comment]
Thank you so much!!!
