### ISSUE TITLE
I see everything but i cant control the music!

### ISSUE THREAD

**Issue by CodeMasterOogway** [ThatGravyBoat/Craftify#61]
I can see the hud I see what song is playing and I logged in but I can't control it at all not even the volume. Am I doing something wrong? This is my first time using this mod so idk. Please help!

**Comment by CodeMasterOogway** [comment]
Also, I use fabric 1.20.1 if that helps.

**Comment by ThatGravyBoat** [comment]
Try restarting, if you are using Spotify then controls on non premium accounts cant be used as Spotify locks that API behind premium accounts

**Comment by CodeMasterOogway** [comment]
Okay, so I just now realized it said it requires Spotify premium... Sorry!
