### ISSUE TITLE
"Essential Notification" in Announce New Song doesn't work

### ISSUE THREAD

**Issue by kristibektashi** [ThatGravyBoat/Craftify#72]
I have both Essential And Craftify installed and I am using Cider as my music service

Minecraft 1.20.1 on Prism Launcher with Fabulously Optimized 5.2.2 modpack plus Craftify v1.11.0 and Essential mod (version is irrelevant since it auto-updates) 

The "Chat Message" option in Announce New Song is working perfectly fine

**Comment by ThatGravyBoat** [comment]
Essential support is for <= 1.12 I left the option in there as to not screw with people if they copy their configs from older versions as I do work on all versions at the same time
