### ISSUE TITLE
Foobar2000 UI Settings

### ISSUE THREAD

**Issue by mariokirby1703** [ThatGravyBoat/Craftify#77]
It would be cool to be able to edit what the UI displays in-game.
Currently, it displays Song Image (which can only be disabled by restarting both Foobar and Minecraft; also an option to make it transparent would be nice), Track Title, and Artist Name. It would be very useful if you'd be able to also show other properties like Album Title, Genre, Composer, etc.

**Comment by ThatGravyBoat** [comment]
Currently, because I want parity with all platforms I support I wont add anything else to the display but if platforms in the future all have the same info I can do that
