### ISSUE TITLE
the image doesnt show

### ISSUE THREAD

**Issue by cuqzo** [ThatGravyBoat/Craftify#78]

**Comment by ThatGravyBoat** [comment]
I need and image and latest.log

**Comment by Anduwu1** [comment]
![image](https://github.com/ThatGravyBoat/Craftify/assets/84476053/05015551-4a3a-40e1-9fa9-c6eaaf2fc817)
I have what I think is the same issue and this is what it looks like for every song.

**Comment by ThatGravyBoat** [comment]
same thing I need latest.log

**Comment by Anduwu1** [comment]
just like default minecraft ones or some other log?

**Comment by ThatGravyBoat** [comment]
in the minecraft logs folder you have a latest.log I need that and then upload it to https://mclo.gs/

**Comment by Anduwu1** [comment]
https://mclo.gs/vFSVK4S

**Comment by ThatGravyBoat** [comment]
This is an issue with how elementa handled images, fixed in dev release will be soon
