### ISSUE TITLE
[Question] How to use shared servers feature?

### ISSUE THREAD

**Issue by Zamtang** [ThatGravyBoat/Craftify#80]
You're doing a great job with your mod. Thanks for making them, but I have a question.

My friends and I are playing with a private fabric server.
We want to listen to songs together, but I want to know more about **how to use the share servers feature**.
No matter how much I googled it, it didn't come up.

I hope you can help me.
thank you

**Comment by ThatGravyBoat** [comment]
Currently the shared servers feature is an API that can be used by other mods to know the song you're listening to on the server, as of right now [Prometheus](https://modrinth.com/mod/prometheus) is the only mod that supports it and that can be setup by being an op and doing `/roles` and then opening the everyone role and then in the permissions adding `heading.music`  and saving (top left) then you can do `/heading music` which when you enable your current server as a shared server in the shared servers menu it will then display above your head the current song you're listening to

**Comment by ThatGravyBoat** [comment]
For further questions if needed can you please join my discord server its listed inside the mods self promo section fo the settings menu, it will allow for faster and easier communication for questions.
