### ISSUE TITLE
report a bug YTMD

### ISSUE THREAD

**Issue by Accardi22** [ThatGravyBoat/Craftify#81]
came to report a bug that might just be a me issue, all the functions work for YTMD but none of the GUI glory works at all. definitely aware that it could be on my end since i have a lot of mods, so ill be looking through the multimc log to see if i spot anything but thought id post here anyway.

**Comment by Accardi22** [comment]
[https://media.essential.gg/85c45c3a-1eb4-41fe-da9a-4ff4c7903200](url)

**Comment by ThatGravyBoat** [comment]
See #82
