### ISSUE TITLE
Album image, song name, and duration not showing

### ISSUE THREAD

**Issue by Leb0** [ThatGravyBoat/Craftify#83]
After going through the process of linking my YTMD and seeing that it works I noticed that even though the song still plays the ui doesn't change at all , I can still skip songs and all of that but for some reason I can't see the name of the song nor the duration in-game, I tried closing YTMD and minecraft but after restarting it still doesn't show what I just mentioned.
If anyone can help me I would appreciate it a lot!

**Comment by MrSupreme12** [comment]
Im also have the problem with this. Maybe YTMD have issue with new Youtube things or Crafity the issue here.

**Comment by Epic428** [comment]
See #81 and #82 the literal two preceding issues before this one.

**Comment by ThatGravyBoat** [comment]
Yeah it requires an update to the implementation due to YTMD updating
