### ISSUE TITLE
option for in-game buttons to use media keys for skipping, starting and stopping music

### ISSUE THREAD

**Issue by BoogieHasFun** [ThatGravyBoat/Craftify#84]
i'd like a way to control Spotify from Minecraft, but i don't have premium so the buttons don't work. i've seen it used in other programs before (like OVR Toolkit) and i also have them on my keyboard but i think it'd be cooler to control my music in Minecraft and it'd be beneficial to users without media keys

i'd start [here](https://start.duckduckgo.com/?t=ffab&q=java+media+keys&ia=web) if you don't know how to do this (don't feel sad for not knowing how, i can't program in Java)

**Comment by ThatGravyBoat** [comment]
I am not going to implement this as its a circumvention of a system Spotify put in place and would be against the developer terms of service I have to follow

**Comment by BoogieHasFun** [comment]
> I am not going to implement this as its a circumvention of a system Spotify put in place and would be against the developer terms of service I have to follow


dang, i wish big companies weren't so strict to gain as much money as possible :(
