### ISSUE TITLE
[Suggestion] Announcement Message

### ISSUE THREAD

**Issue by momenazhar** [ThatGravyBoat/Craftify#85]
Fix multiple artists names having no space after the comma:
`Name,Name` -> `Name, Name`

Also add the tag `${artist}` to show only the main artist of the song, and keep `${artists}` to list all of the artists in the song
![image](https://github.com/ThatGravyBoat/Craftify/assets/67310794/69038af3-8a5f-4d05-9354-48f17ccddd51)

**Comment by ThatGravyBoat** [comment]
Added in 1.13.0
