### ISSUE TITLE
Clicking on the Login button does nothing.

### ISSUE THREAD

**Issue by Gchk34** [ThatGravyBoat/Craftify#87]
I have just downloaded the mod for 1.20.2 and after setting the mod mode (to spotify in my case), the login button just takes me to [https://craftify.thatgravyboat.tech/login](url) which responds with `404 page not found`. 
I have no idea if the build of the mod I got redirects me to the wrong site, or the site has some problem.

**Comment by ThatGravyBoat** [comment]
It was down for a few minutes due to some server maintenance that was being done but it should work now.
