### ISSUE TITLE
Crashes on startup when Spotify is already running

### ISSUE THREAD

**Issue by MicrocontrollersDev** [ThatGravyBoat/Craftify#9]
[Relevant log](https://mclo.gs/kUczaFs)

**Comment by ThatGravyBoat** [comment]
Well seeing as the log does not even say the word craftify besides listing the mods I'm gonna assume its not because of craftify lol

**Comment by MicrocontrollersDev** [comment]
Issue only happens when Craftify is installed and Spotify is playing pre-launch. If Spotify isn’t playing anything, game launches normally. If Craftify isn’t installed, game launches normally. But if Spotify is already running while I launch the game with Craftify I get this crash. But yeah I get that the crash log doesn’t provide much in that regard.

**Comment by ThatGravyBoat** [comment]
Well that's even weirder because I literally don't do anything when it comes to the app, I don't check a single thing when it comes to the app running.

**Comment by MicrocontrollersDev** [comment]
ah sorry worded that poorly. when i said spotify running i meant when spotify is currently playing a song

**Comment by ThatGravyBoat** [comment]
Yeah idk what it can still be as Craftify checks no matter what because I have to check and parse the player because you can start playing a song at anytime so even if you don't have a song playing it will still parse and check the data
