### ISSUE TITLE
Craftily 1.8.9 on Mac

### ISSUE THREAD

**Issue by Redstoner875** [ThatGravyBoat/Craftify#92]
Craftify on Mac doesn't appear to be working, not entirely sure why, 1.8.9 latest version with spotify, I get a "successful" link, but nothing shows in game, playing on desktop app, as well as browser.

**Comment by ThatGravyBoat** [comment]
Craftify does not use any thing related to the system for spotify is goes over the internet so if it does not work its an issue with spotify itself, make sure to try and restarting your game first to see if it works if not create a new issue with more information. Like mod version, mc version, mod loader, operating system, os version
