### ISSUE TITLE
Lyrics Overlay

### ISSUE THREAD

**Issue by aserwebsite** [ThatGravyBoat/Craftify#93]
I think it would be nice to have a little window that shows the lyrics for the song that is currently playing.

I'm not too sure how hard this would be to code or if you would need Spotify Premium for this.

Wouldn't work for some music providers other than YTM, Spotify and AM.

**Comment by ThatGravyBoat** [comment]
As of right now I will not be adding a lyrics overlay for the foreseeable future, I may come back to it in the future but not anytime soon.
