### ISSUE TITLE
Cider 2.0 Update

### ISSUE THREAD

**Issue by Pandaptable** [ThatGravyBoat/Craftify#96]
Cider has just rereleased websockets in the new client so it's now possible to implement cider 2.0 client support. See: [Cider Devlog 2.3.0](https://cidercollective.itch.io/cider/devlog/674855/cider-v230)

**Comment by ThatGravyBoat** [comment]
Duplicate of #40 where I have now marked it as scheduled for next update

**Comment by Pandaptable** [comment]
ah fuck my bad, i did not think to leave a comment on the other issue, sorry!!
